#只能填写两个不能相邻的方块
Overall-Situation:
  A: TCONSTRUCT
  B: CREATE
  #支持PlaceholderAPI
  Tip: '不能摆放两种限制方块相邻放置！'
SelfHomeMain:
  #启用SelfHomeMain插件兼容
  enable: true
  EnableClearExtraBlocks: false
  #精准检测
  CheckA: true
  TileListA:
      - world|POWAH_PLAYER_TRANSMITTER|1
      - world|CREATE_STATIONARY_CONTRAPTION|5
      - chunk|POWAH_ENDER_GATE_SPIRITED|1
      - chunk|MODERN_INDUSTRIALIZATION_NUCLEAR_REACTOR|1
      - world|HOPPER|20
      - chunk|MODERN_INDUSTRIALIZATION_ELECTRIC_MACERATOR|1
      - chunk|MODERN_INDUSTRIALIZATION_ELECTRIC_MIXER|1
      - world|MODERN_INDUSTRIALIZATION_CHEMICAL_REACTOR|10
  #模糊检测
  CheckR: false
  TileListR:
      - world|POWAH_PLAYER_TRANSMITTER|1
      - world|CREATE_STATIONARY_CONTRAPTION|5
      - chunk|POWAH_ENDER_GATE_SPIRITED|1
      - chunk|MODERN_INDUSTRIALIZATION_NUCLEAR_REACTOR|1
      - world|HOPPER|20
      - chunk|MODERN_INDUSTRIALIZATION_ELECTRIC_MACERATOR|1
      - chunk|MODERN_INDUSTRIALIZATION_ELECTRIC_MIXER|1
      - world|MODERN_INDUSTRIALIZATION_CHEMICAL_REACTOR|10



